name: gif
channels:
  - pytorch
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.12.13
  - pip
  - numpy=2.4.3
  - scipy=1.17.1
  - matplotlib=3.10.8
  - pillow=12.1.1
  - pytorch=2.10.0
  - torchvision=0.25.0
  - pip:
      - datasets==4.8.4
      - transformers==5.5.4
      - pytest==9.0.3
